name: koiwave
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.9.13
  - readline=8.2
  - setuptools=75.6.0
  - sqlite=3.47.0
  - tk=8.6.13
  - tzdata=2024b
  - wheel=0.45.1
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.6
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - blinker==1.9.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.0
      - flask==3.1.0
      - frozenlist==1.4.1
      - gtts==2.5.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - itsdangerous==2.2.0
      - jinja2==3.1.3
      - markupsafe==3.0.2
      - multidict==6.1.0
      - openai==1.12.0
      - pathlib==1.0.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.2.1
      - pydub==0.25.1
      - pyjwt==2.9.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.19
      - requests==2.32.3
      - sniffio==1.3.1
      - starlette==0.38.6
      - tqdm==4.67.1
      - twilio==9.3.2
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - uvicorn==0.30.6
      - websockets==13.1
      - werkzeug==3.1.3
      - yarl==1.12.1
      - zipp==3.21.0
